// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vlcn-studio/Categorias.tsx": () => import("../components/mockups/vlcn-studio/Categorias.tsx"),
  "./components/mockups/vlcn-studio/ChatWidget.tsx": () => import("../components/mockups/vlcn-studio/ChatWidget.tsx"),
  "./components/mockups/vlcn-studio/ConfiguradorPremium.tsx": () => import("../components/mockups/vlcn-studio/ConfiguradorPremium.tsx"),
  "./components/mockups/vlcn-studio/Inicio.tsx": () => import("../components/mockups/vlcn-studio/Inicio.tsx"),
  "./components/mockups/vlcn-studio/SubCatalogo.tsx": () => import("../components/mockups/vlcn-studio/SubCatalogo.tsx")
};
