// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vlcn-studio/Categorias.tsx": () => import("../components/mockups/vlcn-studio/Categorias.tsx"),
  "./components/mockups/vlcn-studio/ConfiguradorPremium.tsx": () => import("../components/mockups/vlcn-studio/ConfiguradorPremium.tsx"),
  "./components/mockups/vlcn-studio/Footer.tsx": () => import("../components/mockups/vlcn-studio/Footer.tsx"),
  "./components/mockups/vlcn-studio/Inicio.tsx": () => import("../components/mockups/vlcn-studio/Inicio.tsx"),
  "./components/mockups/vlcn-studio/SubCatalogo.tsx": () => import("../components/mockups/vlcn-studio/SubCatalogo.tsx"),
  "./components/mockups/vlcn-studio/TerminosCondiciones.tsx": () => import("../components/mockups/vlcn-studio/TerminosCondiciones.tsx"),
  "./components/mockups/vlcn-studio/WhatsAppButton.tsx": () => import("../components/mockups/vlcn-studio/WhatsAppButton.tsx")
};
